### PR TITLE
fix: not working m.youtube.com URLs

### LINKED ISSUE #32: Mobile youtube URLs are not downloaded
E.g. `https://m.youtube.com/watch?v=Hz6DHH8UnPE&list=OLAK5uy_mcqI5C6B3GYHv9lx36lUvIw7ysYBABYg0&index=2`

### PR DESCRIPTION
**Pull request by soanvig**
Closes #32

### CODE REVIEW

File: src/Youtube.hs [hunk 1]
```diff
@@ -1,30 +1,36 @@
...
 import Helpers
-import Data.List.Split ( splitOn )
+import Network.URI
 
 isYoutubeHost :: URIAuth -> Bool
-isYoutubeHost auth = uriRegName auth == "youtube.com" || uriRegName auth == "www.youtube.com"
+isYoutubeHost auth =
+  uriRegName auth == "youtube.com"
+    || uriRegName auth == "www.youtube.com"
+    || uriRegName auth == "m.youtube.com"
```
Comment (soanvig) [inline src/Youtube.hs:14]: add www.m.youtube.com as well
